 const WORDS = {
    Beginner: [
  'the','and','for','are','but','not','you','all','can','her','was','one','our','out','day','get','has','him','his','how','man','new','now','old','see','time','two','way','who','boy','did','its','let','put','say','she','too',
  'use','heat','light','water','house','plant','earth','music','story','friend','family','school','animal','people','world','happy','laugh','smile','dance','dream','peace','love','hope','faith','brave','kind','strong','smart',
  'funny','quick','quiet','loud','bright','clean','fresh','sweet','blue','green','red','yellow','black','white','small','big','tall','short','fast','slow','soft','hard','near','far','good','bad','best','worst','early','late',
  'young','old','right','left','up','down','in','out','on','off','over','under','before','after','first','last','next','then','walk','run','jump','play','read','write','draw','sing','cook','eat','drink','sleep','work','help',
  'talk','listen','watch','build','make','grow','open','close','start','stop','begin','end','win','lose','try','learn','teach','count','think','know','feel','touch','smell','taste','see','hear','move','stay','live','die',
  'bring','take','find','give','call','ask','show','look','come','go','wait','wish','wear','buy','sell','send','keep','change','meet','need','want','like','love','hate','share','care','join','play','stay','rest','smile','shine'
],
  Intermediate: [
  'because','between','always','almost','around','before','after','again','another','answer','beautiful','believe','better','beyond','brother','brought','building','careful','center','chance','change','choose','circle','clothes','country','course','cousin','create','decide','develop','different','direction','discover','doctor','during','eight','enough','especially','example','family','favorite','feeling','finish','follow','forgot','forward','happen','hundred','important','instead','interesting','journey','language','machine','moment','money','morning','mountain','neighbor','nothing','number','office','outside','parent','people','perhaps','person','picture','please','police',
  'problem','question','quickly','reason','remember','return','school','season','second','sentence','several','should','sister','something','sometimes','special','station','story','strange','student','study','subject','sudden','summer','teacher','through','together','tonight','tomorrow','understand','village','weather','weekend','window','without','wonder','world','writing','yellow','accident','advice','ancient','anybody','arrive','artist','attempt','battle','beautifully','belong','border','breathe','bridge','butterfly','captain','carefully','celebrate','certain','climate','collect','command','company','complete','consider','contain','control','correct','courage','damage',
  'december','delicious','describe','destroy','developed','diamond','difference','discuss','education','electric','emergency','energy','enjoy','enough','escape','experience','explain','famous','feather','festival','future','garden','general','government','grocery','history','holiday','hospital','imagine','include','information','island','knowledge','language','library','message','mountain','natural','necessary','neither','occasion','opinion','package','pattern','peaceful','performance','perfect','perhaps','physical','planet','pleasure','polite','popular','position','positive','possible','powerful','prepare','present','prevent','private','produce','promise','protect','provide','purpose','quality','quietly','quickness','rainbow','realize','receive','recognize','recommend','record','refresh','region','regular','relation','relax','release','remember','replace','report','require','respect','respond','result','return','reward','safety','satisfy','science','seasonal','secret','secure','sensible','sentence','separate','serious','service','shadow','shelter','shining','shoulder','silence','similar','simple','single','situation','society','solution','someone','something','sometimes','somewhere','southern','specialist','speech','spirit','station','strength','stretch','student','subject','success','suggest','summer','support','surface','surprise','surround','system','teacher','technical','temperature','together','tomorrow','tonight','traffic','training','translate','transport','trouble','trust','understand','uniform','universe','unknown','unusual','useful','usually','valuable','variety','vehicle','village','visitor','victory','weather','welcome','western','whisper','wonderful','wooden','working','writing','yourself','yesterday','adventure','behavior','birthday','bicycle','breathe','building','capture','careless','carrier','century','channel','chapter','comfort','compare','concert','connect','contain','courage','curious','custom','damage','decide','deliver','demand','depend','describe','detail','difference','disappear','discover','disease','education','election','emotion','employer','encourage','engineer','enjoyment','enough','entrance','environment','escape','especially','evidence','example','exercise','explain','factory','famous','fashion','feature','festival',
  'finally','foreign','freedom','friendly','function','future','gallery','general','governor','handsome','healthy','holiday','honest','imagine','improve','increase','independent','individual','industry','influence','information','instrument','interest','journey','language','laughter','library','machine','manage','manner','material','measure','medicine','memory','mention','message','method','mirror','moment','movement','musical','natural','necessary',  'neighbor','normal','notice','object','officer','opinion','opposite','ordinary','original','package','paragraph','partner','passenger','pattern','peaceful','perfect','personal','picture','pleasure','pollution','popular','position',
  'possible','powerful','practice','prepare','present','pressure','previous','probably','process','produce','product','progress','project','promise','protect','provide','purpose'
],


      
  
   Advanced: [
  'abandon','absolute','abstract','academy','achievement','acoustic','adaptation','advantage','affection','agreement','ambition','analysis','ancestor','anonymous','appliance','approach','architect','arrangement','assistant',
  'atmosphere','attention','audience','authority','background','behavior','biography','brilliant','capacity','category','celebration','challenge','character','chemical','circumstance','civilization','colleague','combination',
  'communication','community','competition','complicated','conclusion','condition','conference','confidence','connection','consequence','consideration','construction','contribution','convenient','cooperation','correction',
  'creativity','curiosity','decision','definition','democracy','department','description','determination','development','difference','difficulty','direction','discovery','distinction','education','efficiency','electricity',
  'employment','encouragement','environment','establishment','evaluation','experience','experiment','expression','foundation','generation','government','identification','imagination','importance','improvement','independent',
  'information','initiative','innovation','inspiration','intelligence','interaction','introduction','investigation','knowledge','leadership','literature','management','mathematics','measurement','motivation','movement','necessity',
  'observation','opportunity','organization','participation','performance','personality','philosophy','population','possibility','preparation','presentation','president','principle','probability','production','professional',
  'protection','publication','qualification','reaction','realization','recommendation','relationship','requirement','reservation','resolution','revolution','satisfaction','situation','stability','statement','structure',
  'technology','temperature','tradition','transportation','university','understanding','volunteer','wonderful','achievement','acknowledge','announcement','architecture','championship','collaboration','combination','comparison',
  'concentration','conversation','coordination','corporation','description','determination','development','discrimination','distribution','documentation','education','entertainment','evaluation','examination','experience',
  'improvement','information','introduction','maintenance','management','measurement','motivation','organization','participation','performance','personality','philosophy','population','preparation','presentation','production',
  'accomplishment','administration','advertisement','agriculture','anniversary','application','appointment','appreciation','arrangement','association','atmosphere','availability','biological','calculation','certificate',
  'circumstance','combination','communication','comparison','competition','comprehensive','concentration','conclusion','conference','confidence','connection','consequence','consideration','construction','consultation',
  'contribution','cooperation','coordination','corporation','correction','declaration','demonstration','determination','development','difference','difficulty','direction','discrimination','distribution','documentation',
  'education','efficiency','electricity','employment','encouragement','environment','establishment','evaluation','examination','experience','experiment','expression','foundation','generation','government','identification',
  'imagination','importance','improvement','independent','information','initiative','innovation','inspiration','intelligence','interaction','introduction','investigation','knowledge','leadership','literature','management',
  'mathematics','measurement','motivation','movement','necessity','observation','opportunity','organization','participation','performance','personality','philosophy','population','possibility','preparation','presentation',
  'president','principle','probability','production','professional','protection','publication','qualification','reaction','realization','recommendation','relationship','requirement','reservation','resolution','revolution',
  'satisfaction','situation','stability','statement','structure','technology','temperature','tradition','transportation','university','understanding','volunteer','wonderful','scientific','biological','linguistic','psychology',
  'philosophy','anthropology','architecture','metaphor','paradigm','criterion','sociology','artificial','intelligence','machine','learning','neural','network','cognitive','computation','sustainability','biodiversity',
  'conservation','infrastructure','legislation','international','collaboration','innovation','entrepreneurship','negotiation','evaluation','optimization','implementation','synchronization','accountability','credibility',
  'responsibility','transparency','governance','leadership','management','entrepreneur','stakeholder','globalization','distribution','industrialization','investment','productivity','sustainability','transportation',
  'communication','representation','transformation','revolutionary','psychological','technological','environmental','biochemical','pharmaceutical','astronomical','metaphysical','constitutional','organizational','institutional',
  'professionalism','philanthropy','quantitative','qualitative','methodology','disciplinary','interdisciplinary','crossfunctional','biotechnology','nanotechnology','cybersecurity','cryptocurrency','automation','simulation',
  'integration','virtualization','optimization','visualization','theoretical','practical','experimental','computational','contextual','sociocultural','biomedical','diagnostic','therapeutic','regenerative','educational',
  'transformational','dimensional','hypothesis','empirical','systematic','conceptual','sustainability','reliability','adaptability','resilience','flexibility','scalability','accountability','credibility','viability','transparency',
  'collaborative','cooperative','productive','constructive','comprehensive','analytical','synthetic','evaluative','interpretive','comparative','quantitative','qualitative','correlative','predictive','cognitive','creative',
  'innovative','progressive','transformative','evolutionary','revolutionary'
]


   
   };
